### PR TITLE
A number of fixes for python interface for MPSolve

### PR DESCRIPTION
**Pull request by kagalenko-m-b**
* set_coefficients() does not work correctly on string inputs
    * set_coefficients() only sets the real part
    * no way to see polynomial coefficients
    * function mps_chebyshev_poly_set_coefficient_s() does not exist in the library, but mpsolve.py calls it

### CODE REVIEW

**Comment by robol** [comment]
Dear Michael, 
thank you for contributing to MPSolve! It will probably take me a few more days to find some time to review the changes, but I expect to merge them during next week at the latest. 

Best regards, -- Leonardo.

**Comment by kagalenko-m-b** [comment]
For some reason MPSolve, used via python interface, does not give correct results on Wilkinson polynomial. Test file below
#==
import mpsolve  as mps
import numpy as np

#
M = 20
D = [m for m in range(1,M+1)]
phi = np.zeros(M + 1,dtype=int)
phi[0] = 1.0
for m in range(M):
    phi0 = phi[0:m+1].copy()
    phi[:] = 0
    phi[1:m+2] = phi0
    phi[:m+1] = phi[:m+1] - D[m]*phi0

ctx = mps.Context()
poly=mps.MonomialPoly(ctx, M)
for k in range(len(phi)):
    poly.set_coefficient(k, "{:d}".format(phi[k]))
    # poly.set_coefficient(k, int(phi[k]))
Dm = ctx.solve(poly)
print("Wilkinson polynomial roots:",Dm)
print("\nMax inclusion radius = {:e}".format(max(ctx.get_inclusion_radii())))

**Comment by kagalenko-m-b** [comment]
For some reason set_coefficient() does not work correctly
```python
import mpsolve  as mps
import numpy as np
#
M = 20
D = [m for m in range(1,M+1)]
phi = np.zeros(M + 1,dtype=int)
phi[0] = 1.0
for m in range(M):
    phi0 = phi[0:m+1].copy()
    phi[:] = 0
    phi[1:m+2] = phi0
    phi[:m+1] = phi[:m+1] - D[m]*phi0
ctx = mps.Context()
poly_s = mps.MonomialPoly(ctx, M)
poly_i = mps.MonomialPoly(ctx, M)
poly_d = mps.MonomialPoly(ctx, M)
for k in range(len(phi)):
    poly_s.set_coefficient(k, "{:d}".format(phi[k]))
    poly_i.set_coefficient(k, int(phi[k]))
    #poly_d.set_coefficient(k, float(phi[k]))
cf_s = poly_s.get_coefficients()
cf_i = poly_i.get_coefficients()
#cf_d = poly_d.get_coefficients()
print("\nset_coefficient() error:{:e} {:e}\n".format(max(abs(cf_s-phi)),max(abs(cf_i-phi))))
```

**Comment by kagalenko-m-b** [comment]
MPSolve does not seem to get correct results for the Wilkinson polynomial. C example added.

**Comment by kagalenko-m-b** [comment]
This function in mpc.c:
``` C
void
mpc_init (mpc_t c)
{
  printf ("mpc_init () called\n");
  abort ();
 ....
}
```
Seems an oversight or unfinished? Computational library shouldn't call abort(), it brings down the whole program.

**Comment by kagalenko-m-b** [comment]
I have to say, the MPSolve is an excellent software, thank you very much for making it opensource

**Comment by kagalenko-m-b** [comment]
I have to say, the MPSolve is an excellent software, thank you very much for making it opensource

**Pull request merged**
